### ISSUE TITLE
Upgrade to Node.js 16.x

### ISSUE THREAD

**Issue by clintonb** [Reviewable/appengine-remove-action#14]
GitHub has deprecated Node 12.x for actions. This action needs to be updated to use Node 16.x.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by pkaminski** [comment]
I updated the action to modern dependencies and a Node 16 runner but haven't had a chance to test it yet.  (The build output looks a bit weird to my eyes but I'm not very familiar with this code.)  I published [pre-release v3.0.0](https://github.com/Reviewable/appengine-remove-action/releases/tag/v3.0.0); I'll test it in due course, but if you'd like to do so sooner please let me know how it goes!

**Comment by pkaminski** [comment]
I tried it out and appears to work (v3.0.0).
