### ISSUE TITLE
Usage example still refers to v2 specifically

### ISSUE THREAD

**Issue by coolstuff-michael** [Reviewable/appengine-remove-action#4]
Slight issue I came across was that the version in the documentation is specifically set at v2 (`uses: Reviewable/appengine-remove-action@v2`). This was a little problematic for me as the fix for `service_name` was added in v2.1.1

**Comment by pkaminski** [comment]
Yeah, I always forget that action versions are baked right into the workflow files.  Fixed.

**Comment by coolstuff-michael** [comment]
@pkaminski Same thing again for v2.1.2 :smile:

**Comment by pkaminski** [comment]
Argh, I updated the example but forgot to push.
